### ISSUE TITLE
[PE-D][Tester A] Listing All Trips - Minor input validation

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W14-4/tp#79]
Consider adding a validation check or exception handling for listall command. 

![8.png](https://raw.githubusercontent.com/V4Vern/ped/main/files/a7bc364d-aac7-4c9d-8e4b-1beaad4c8fab.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: V4Vern/ped#6

**Comment by CerealMiller** [comment]
changed NewParser and ListCommand so that 'list <not_trip_status> prints error message.
