### ISSUE TITLE
[PE-D][Tester A] Reviewing Trips - handling of invalid score

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W14-4/tp#81]
The program does not print out a valid message to inform the user in the event that a very high positive number or very low negative number is entered.

![9.png](https://raw.githubusercontent.com/V4Vern/ped/main/files/96bc0969-00e0-47e4-9fb4-e018a168bb2c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: V4Vern/ped#7

**Comment by CerealMiller** [comment]
Fixed in PR #125

**Comment by CerealMiller** [comment]
Fixed in PR #125
