### ISSUE TITLE
[PE-D][Tester A] Reading Trip Reviews - Command does not seem to work

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W14-4/tp#84]
Command readreview does not seem to work. It prints out " seedu.voyagers.classes.Review@1d8d30f7" as shown in the image.

![10.png](https://raw.githubusercontent.com/V4Vern/ped/main/files/9adb21c8-e9dd-477e-8239-aef19c3ec227.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: V4Vern/ped#8

**Comment by CerealMiller** [comment]
Fixed with PR #122
